# #Analyzer: コードに言語仕様で指定されているエラーや警告などのバグがないかを解析する。
# #Linter: コードがスタイルガイドラインに準拠しているかを解析する。

# include: package:flutter_lints/flutter.yaml
include: package:lint/strict.yaml # lint
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.gql.dart
    - lib/**/*.freezed.dart
