name: bubu_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.7+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_storage: ^11.2.8
  flutter:
    sdk: flutter
  flutter_carousel_slider: ^1.1.0
  flutter_datetime_picker_plus: ^2.1.0
  flutter_hooks: ^0.18.6
  flutter_image_compress: ^2.0.4
  flutter_local_notifications: ^16.1.0
  flutter_nearby_connections: ^1.1.1
  flutter_secure_storage: ^8.1.0
  flutter_slidable: ^3.0.0
  freezed_annotation: ^2.4.1
  google_mobile_ads: ^3.1.0
  hooks_riverpod: ^2.3.8
  image_picker: ^0.8.9
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0+4
  path_provider: ^2.1.1
  riverpod_annotation: ^2.1.2
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.11
  vibration: ^1.8.3
  visibility_detector: ^0.4.0+2

dev_dependencies:
  # flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  lint: ^2.0.0
  riverpod_generator: ^2.2.4

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/

  fonts:
    - family: Normal
      fonts:
        - asset: assets/font/Noto_Sans_JP/NotoSansJP-VariableFont_wght.ttf
          weight: 100
        - asset: assets/font/Noto_Sans_JP/NotoSansJP-VariableFont_wght.ttf
          weight: 200
        - asset: assets/font/Noto_Sans_JP/NotoSansJP-VariableFont_wght.ttf
          weight: 300
        - asset: assets/font/Noto_Sans_JP/NotoSansJP-VariableFont_wght.ttf
          weight: 400
        - asset: assets/font/Noto_Sans_JP/NotoSansJP-VariableFont_wght.ttf
          weight: 500
        - asset: assets/font/Noto_Sans_JP/NotoSansJP-VariableFont_wght.ttf
          weight: 600
        - asset: assets/font/Noto_Sans_JP/NotoSansJP-VariableFont_wght.ttf
          weight: 700
 
